### ISSUE TITLE
Any simple helpful wiki how to run it ?

### ISSUE THREAD

**Issue by herrygoon** [MarkShawn2020/ScrapyAnything#1]
1.how to use the captcha by hand, what the format of the accouts.txt ?
  I have start the qt GUI,click the start or submit ,but without any info output in the console
2.how to start the crawler ? do we need any other config?
3.does it support distributed?how can we support it ?

thanks.

**Comment by MarkShawn2020** [comment]
Thanks for your attention.
The project is for those developers familiar with SCRAPY, but with no or little time/ability to hack specific websites.
Any of my solutions to these websites can only be a reference rather than a framework which can boost into use(especially with time passed).
The questions of 1, 2 you mentioned requires you to dive deep into the project details, try to figure out what I am doing and what they are for; and the questions of 3, 4 are relative the use of scrapy itself, you should have a glance at their official wiki.
Thanks again.
